using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DotnetHandler.SourceGenerators;

[Generator]
public sealed class HandlerRegistrationGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat NullableFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(static s => s is not null)
            .Select(static (s, _) => s!);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(candidates.Collect()),
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> symbols,
        SourceProductionContext context)
    {
        var handlerInterface = compilation.GetTypeByMetadataName("DotnetHandler.Abstractions.IRequestHandler`2");
        var listenerInterface = compilation.GetTypeByMetadataName("DotnetHandler.Abstractions.IEventListener`1");

        if (handlerInterface is null && listenerInterface is null)
            return;

        var handlers = new List<(string Request, string Response, string Handler)>();
        var listeners = new Dictionary<string, List<string>>();

        foreach (var symbol in symbols.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            if (symbol.IsAbstract || symbol.IsStatic)
                continue;

            foreach (var iface in symbol.AllInterfaces)
            {
                if (handlerInterface is not null &&
                    SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, handlerInterface))
                {
                    handlers.Add((
                        iface.TypeArguments[0].ToDisplayString(NullableFormat),
                        iface.TypeArguments[1].ToDisplayString(NullableFormat),
                        symbol.ToDisplayString(NullableFormat)));
                }

                if (listenerInterface is not null &&
                    SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, listenerInterface))
                {
                    var eventType = iface.TypeArguments[0].ToDisplayString(NullableFormat);
                    if (!listeners.ContainsKey(eventType))
                        listeners[eventType] = new List<string>();
                    listeners[eventType].Add(symbol.ToDisplayString(NullableFormat));
                }
            }
        }

        if (handlers.Count == 0 && listeners.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by DotnetHandler.SourceGenerators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace DotnetHandler.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedRegistrationExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::DotnetHandler.Registration.ApplicationBuilder UseGeneratedHandlers(");
        sb.AppendLine("            this global::DotnetHandler.Registration.ApplicationBuilder app)");
        sb.AppendLine("        {");

        if (handlers.Count > 0)
        {
            sb.AppendLine("            app.Handlers(h =>");
            sb.AppendLine("            {");
            foreach (var (request, response, handler) in handlers)
            {
                sb.AppendLine($"                h.Register<{request}, {response}>()");
                sb.AppendLine($"                 .HandledBy<{handler}>();");
            }
            sb.AppendLine("            });");
        }

        if (listeners.Count > 0)
        {
            sb.AppendLine("            app.Events(e =>");
            sb.AppendLine("            {");
            foreach (var pair in listeners)
            {
                sb.Append($"                e.Register<{pair.Key}>()");
                foreach (var listenerType in pair.Value)
                {
                    sb.AppendLine();
                    sb.Append($"                 .Subscribe<{listenerType}>()");
                }
                sb.AppendLine(";");
            }
            sb.AppendLine("            });");
        }

        sb.AppendLine("            return app;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            "DotnetHandlerGeneratedRegistration.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
